import { createSelector, createEntityAdapter } from "@reduxjs/toolkit"
import { apiSlice } from "../../app/api/apiSlice"

const blogsAdapter = createEntityAdapter({})

const initialState = blogsAdapter.getInitialState()

export const blogsApiSlice = apiSlice.injectEndpoints({
  endpoints: builder => ({
    getBlogs: builder.query({
      query: () => '/blogs',
      validateStatus: (response, result) => {
        return response.status === 200 && !result.isError
      },
      // specifies that unused data will be retained for 5 seconds.
      keepUnusedDataFor: 5,
      transformResponse: responseData => {
        const loadedBlogs = responseData.map(blog => {
          blog.id = blog._id
          return blog
        })
        // setAll(currentState,replace the currentState)
        return blogsAdapter.setAll(initialState, loadedBlogs)
      },
      providesTags: (result, error, arg) => {
        console.log(result)
        if (result?.ids) {
          return [
            { type: 'Blog', id: 'LIST' },
            ...result.ids.map(id => ({ type: 'Blog', id }))
          ]
        } else return [{ type: 'Blog', id: 'LIST' }]
      }
    })
  })
})

export const {
  //  hook generated by the API slice, providing access to the 
  useGetBlogsQuery
} = blogsApiSlice


// selector function retrieves the result of the getBlogs endpoint query from the Redux store

// if the getBlogs query has been executed and completed successfully, it returns an object with the following properties:

// data: The data received from the API response.
// status: The status of the query, such as 'fulfilled' for a successful request.
// error: If an error occurred during the query, this property will hold the error object.
// If the getBlogs query is still in progress or has not been executed yet, the selector will return an object with the following properties:

// data: undefined or the previously fetched data if available.
// status: The status of the query, such as 'pending' or 'idle'.
// error: undefined.

// gets the query result data
export const selectBlogsResult = blogsApiSlice.endpoints.getBlogs.select()
console.log('selectBlogsResult', selectBlogsResult)


// If the inputs remain the same between consecutive calls, the selector will return the cached result instead of recomputing it
// access the extracted data property from the blogsResult object in your Redux-connected components.
//  The selector will only recalculate its value if the selectBlogsResult result changes
const selectBlogsData = createSelector(
  selectBlogsResult,
  blogsResult => blogsResult.data
)
console.log('selectBlogsData', selectBlogsData)

export const {
  selectAll: selectAllBlogs,
  selectById: selectById,
  selectIds: selectBlogIds
  // The state argument passed to the selectBlogsData selector represents the current state of the Redux store. 
  // It is provided automatically by the Redux store when the selector is called. 
  // The state argument allows the selector to access the relevant data from the Redux store,
  //  in this case, the blogsResult object.
} = blogsAdapter.getSelectors(state => selectBlogsData(state) ?? initialState)

console.log(blogsAdapter.getSelectors(state))