

// generate a set of pre-defined functions and utilities for working with entity collections in Redux

const usersAdapter = createEntityAdapter({})

const initialState = usersAdapter.getInitialState()

// initialState:
// {
//   ids: [],
//   entities: {},
// }

const usersReducer = (state = initialState, action) => {
  // Handle actions to add, update, or remove users using the adapter's reducer
  // state = usersAdapter.reducer(state, action);
  // ...
}

// Selectors generated by the adapter
const {
  selectAll: selectAllUsers,
  selectById: selectUserById,
  selectIds: selectUserIds,
} = usersAdapter.getSelectors(state => state.users)

export {
  usersReducer,
  selectAllUsers,
  selectUserById,
  selectUserIds,
}
