// The apiSlice object generated by createApi includes several properties, including reducer, middleware, and endpoints, among others.

// This slice object includes a reducer to manage cached data, a middleware to manage cache lifetimes and subscriptions, and selectors and thunks for each endpoint.
//  If you imported createApi from the React-specific entry point, it also includes auto-generated React hooks for use in your components.